version: '3.8'

services:
  postgres:
    image: docker.io/library/postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "54321:5432"
    volumes:
      # 将宿主机 ./data/postgres 映射为容器内的数据目录
      - ./data/postgres:/var/lib/postgresql/data
      # 可选：初始化 SQL 脚本
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: docker.io/library/redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      # 数据持久化
      - ./data/redis:/data
      # 可选：挂载自定义配置文件
      # - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      # - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    command: ["redis-server", "--appendonly", "yes"]
    # 如果使用自定义配置，则改为：
    # command: ["redis-server", "/usr/local/etc/redis/redis.conf"]